package org.ditw.pmxml.model

object Constants extends Serializable {

  object XmlTags extends Serializable {
    val PubmedArticle = "PubmedArticle"
    val MedlineCitation = "MedlineCitation"
    val PMID = "PMID"
    val IdType = "IdType"
    val PubmedData = "PubmedData"
    val PublicationStatus = "PublicationStatus"
    val ArticleIdList = "ArticleIdList"
    val ArticleId = "ArticleId"
    val ISSN = "ISSN"
    val Title = "Title"
    val PubDate = "PubDate"
    val Year = "Year"
    val Month = "Month"
    val Day = "Day"
    val Journal = "Journal"
    val Article = "Article"
    val JournalIssue = "JournalIssue"
    val Label = "Label"
    val NlmCategory = "NlmCategory"
    val _Abstract = "Abstract"
    val _AbstractText = "AbstractText"
    val _AuthorList = "AuthorList"
    val ArticleDate = "ArticleDate"
    val _Author = "Author"
    val LastName = "LastName"
    val ForeName = "ForeName"
    val Initials = "Initials"
    val AffiliationInfo = "AffiliationInfo"
    val Affiliation = "Affiliation"
    val Source = "Source"
    val ValidYN = "ValidYN"
    val DateType = "DateType"
    val _Identifier = "Identifier"
    val IssnType = "IssnType"
    val DescriptorName = "DescriptorName"
    val UI = "UI"
    val MajorTopicYN = "MajorTopicYN"
    val QualifierName = "QualifierName"
    val _MeshHeading = "MeshHeading"
    val MeshHeadingList = "MeshHeadingList"
    val CollectiveName = "CollectiveName"
    val MedlineDate = "MedlineDate"
  }

}
